# file: ansible-kafka/tasks/dependencies.yml

- name: Kafka | Make sure the kafka dependencies are installed
  action: apt pkg={{ item }} state=present
  with_items:
    - supervisor

- service: name=supervisor state=started enabled=yes
